[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gnumake", "gcc"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"

[start]
cmd = "npm start"
